### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by ChrisGangs** [twofacejester/RoR2SkillSwapper#1]
Not sure how to find the exact problem.

however i believe something in the mscorlib is messing with multiplayer.

i used two computers with the exact same mod setup and files. they function correctly in single player.  

however when playing with others only the host spawns with a pod. the rest are shown in the tab menu but do not drop down or get shown on the side. 

i also added the mscorlib because of the PlatformNotSupportedException log output

**Comment by twofacejester** [comment]
Sorry for the late reply, notifications were off for whatever reason.

This shouldn't be an issue on the latest release as it's on BepInEx, and from some quick testing, doesn't seem to be happening.
