### ISSUE TITLE
Incorrect Skill Names

### ISSUE THREAD

**Issue by FluffyBiskit** [twofacejester/RoR2SkillSwapper#2]
I've attempted to swap all of the Engineer's default skills onto other characters and none of the handles I have tried seem to work.

Those include all case sensitive iterations such as: "FireGrenade" "fireGrenade" "Firegrenade" "FIREGRENADE" "firegrenade" etc.

This was attempted for the skills FireGrenade, PlaceMine, PlaceBubbleShield, PlaceTurret.

**Comment by twofacejester** [comment]
Sorry for the late reply, notifications were off for some reason.

I can't reproduce this issue on the latest release.

Survivor used: Mage
Skills:
* FireGrenade
* PlaceMine
* PlaceBubbleShield
* PlaceTurret
Commands:
* /swap Mage 0 FireGrenade
* /swap Mage 1 PlaceMine
* /swap Mage 2 PlaceBubbleShield
* /swap Mage 3 PlaceTurret
