### ISSUE TITLE
did not load because "illegal format"

### ISSUE THREAD

**Issue by Manka-Muakido** [twofacejester/RoR2SkillSwapper#3]
![image](https://user-images.githubusercontent.com/39040633/58226377-ccbc3500-7cfc-11e9-9c4d-64e99b418652.png)

**Comment by twofacejester** [comment]
Looking into it, though it may take awhile. The update (both game and the mod loader) broke a few things.

**Comment by twofacejester** [comment]
Fixed in 96ff8b974c62d5fdca85325f156c4b4f7903311b (release v0.3.2)
